### ISSUE TITLE
Changes in toolchanger.py missing

### ISSUE THREAD

**Issue by piposa** [DraftShift/klipper-toolchanger#1]
The latest commit (Only allow one type of stepper driver, add option to enable toolless …
…homing) introduced stepper_driver and homing_toollless to the cfg files. The corresponding changes to toolchanger.py are missing, so klipper is not happy and can't be started.

**Comment by BrewNinja** [comment]
Not sure if you got an answer somewhere else or not yet, but, this is still a WIP and probably shouldn't be used yet.
