### ISSUE TITLE
Disable tap probe to allow other probes

### ISSUE THREAD

**Issue by Rneil-ca** [DraftShift/klipper-toolchanger#15]
Hi I want to be able to disable the tap probe portion of this to allow me to use other probes (I want to use an eddy probe).  But after looking at this it seems like the tool_probe module is deeply integrated into the rest of the repository and there is no easy way to disable it.  Is there an easy way to disable it?

Thanks you for you all your work on this project.

Ryan

**Comment by TheSin-** [comment]
This isn’t an issue this is a requirement atm, I’m going to close this as an issue isn’t required for this.  It is very much part of it with no current options.  We are working on it but there is no eta and no promises.  Current tap is required
